### ISSUE TITLE
Follow symlinks inside repo

### ISSUE THREAD

**Issue by blakemcbride** [Alcaro/GitBSLR#4]
In your docs, you state "Symlinks to anywhere inside the repo are still symlinks".  This is a problem for me in the following situation:

I have a "build" directory that everything gets built under.  This is added to .gitignore.  Gradle builds my JavaDocs under the build directory.  I want those included in my git repo.  I put s symbolic link from under my 'docs' directory to the 'javadoc' directory under the 'build' directory.  If your program allows symbolic links within my repo all would work but it doesn't because of that restriction.

**Comment by Alcaro** [comment]
Guess: Making build/docs/ link to docs/ won't work because something keeps doing rm -r build/*.

Yes, this is on the todo list already (https://github.com/Alcaro/GitBSLR/issues/2#issuecomment-399440401). I'll get to it at some point. I should explain the rationale for keeping in-repo links more clearly, too.
